sudo: required
language: go
dist: xenial

go:
- 1.13.4

before_script:
  - if [ "$DOCKER_USERNAME" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - git clone --depth 1 -b "k8s-v1.18.2" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/k8s-create.sh -s
  - git clone --depth 1 -b "tickets/DM-24587" --single-branch https://github.com/lsst/qserv-operator
  - ./qserv-operator/deploy/qserv.sh --dev
  - kubectl apply -k ./qserv-operator/base
  - ./qserv-operator/wait-qserv-ready.sh

script:
  - ./build-image.sh
  - ./create-ingest.sh
  - ./load-queue.sh
  - ./init.sh
  - ./ingest-chunks.sh
  - ./register.sh
  - ./query.sh


