sudo: required
language: go
dist: xenial

go:
- 1.13.4

before_script:
  - if [ "$DOCKER_USERNAME" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - git clone --depth 1 -b "k8s-v1.18.2" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/k8s-create.sh -s
  - git clone --depth 1 -b "tickets/DM-24587" --single-branch https://github.com/lsst/qserv-operator
  - ./qserv-operator/deploy/qserv.sh --dev
  - kubectl apply -k ./qserv-operator/base
  - ./qserv-operator/wait-qserv-ready.sh

script:
  - . ./env.sh
  - ./build-image.sh
  - ./job.sh queue
  - ./job.sh init
  - ./job.sh chunks
  - ./job.sh register
  - ./copy-emptychunk.sh
  # FIXME restart qserv to refresh xrootd cache
  - kubectl delete pod -l app=$INSTANCE
  - ./qserv-operator/wait-qserv-ready.sh
  - ./query.sh


