sudo: required
language: go
dist: xenial

go:
- 1.13.4

before_script:
  - if [ "$DOCKER_USERNAME" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - git clone --depth 1 -b "k8s-v1.18.0" --single-branch https://github.com/k8s-school/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh -s

script:
  - ./create-ingest-pod.sh
  - ./init.sh
  - ./load-chunks.sh
  - ./register.sh
  - ./query.sh


