apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shell
  name: shell
spec:
  containers:
  - command:
    - sleep
    args:
    - 3600
    image: qserv/replica:tools-w.2018.16-1307-g3b2335a-dirty
    name: shell
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
