commonLabels:
  org: lsst
  app: qserv

configMapGenerator:
- name: config-ingest
  files:
  - ingest.yaml
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

