apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: qserv-ingest-
spec:
  entrypoint: ingest
  volumes:
  - name: repl-creds
    secret:
      secretName: secret-repl-creds-qserv
  arguments:
    parameters:
    - name: image
      # supertransactions is the number of pods running concurrent super-transactions
    - name: supertransactions
      value: 10
  templates:
  - name: ingest-step
    inputs:
      parameters:
      - name: script
    container:
      command:
        - "{{inputs.parameters.script}}"
      image: "{{workflow.parameters.image}}"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: repl-creds
          mountPath: /home/qserv/.lsst
  - name: transactions
    resource:
      action: create
      successCondition: status.succeeded = {{workflow.parameters.supertransactions}}
      failureCondition: status.failed > 0
      manifest: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          generateName: qserv-ingest-transactions-
        spec:
          parallelism: {{workflow.parameters.supertransactions}}
          template:
            spec:
              containers:
              - name: ingest
                command:
                - ingest-chunks.sh
                args:
                - "{{workflow.parameters.supertransactions}}"
                image: {{workflow.parameters.image}}
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - name: repl-creds
                    mountPath: /home/qserv/.lsst
                  - name: config
                    mountPath: /config
              restartPolicy: Never
              volumes:
                - name: repl-creds
                  secret:
                    secretName: secret-repl-creds-qserv
                - name: config
                  configMap:
                    name: config-ingest
          backoffLimit: 0
  - name: main
    dag:
      tasks:
      - name: queue
        template: ingest-step
        arguments:
          parameters: [{name: script, value: load-queue.sh}]
      - name: register
        template: ingest-step
        arguments:
          parameters: [{name: script, value: register.sh}]
      - name: transactions
        template: transactions
        dependencies: [queue, register]
      - name: check-transactions
        template: ingest-step
        arguments:
          parameters: [{name: script, value: check-transactions.sh}]
        dependencies: [transactions]
      - name: publish
        template: ingest-step
        arguments:
          parameters: [{name: script, value: publish.sh}]
        dependencies: [check-transactions]
      - name: index-tables
        template: ingest-step
        arguments:
          parameters: [{name: script, value: index-tables.sh}]
        dependencies: [publish]
      - name: validate
        template: ingest-step
        arguments:
          parameters: [{name: script, value: validate.sh}]
        dependencies: [index-tables]
