apiVersion: batch/v1
kind: Job
metadata:
  name: ingest-index-tables
spec:
  template:
    spec:
      containers:
      - name: index 
        env:
        - name: "REQUESTS_CA_BUNDLE"
          valueFrom:
            configMapKeyRef:
              name: config-data-url
              key: REQUESTS_CA_BUNDLE
        volumeMounts:
        - name: config-data-url
          mountPath: /config-data-url
      restartPolicy: Never
      volumes:
        - name: config-data-url
          configMap:
            name: config-data-url
