commonLabels:
  org: lsst
  app: qserv

resources:
- dev.yaml

configMapGenerator:
- name: config-data-url
  literals:
  - DATA_URL="https://raw.githubusercontent.com/lsst-dm/qserv-ingest/master/data/example_db/"
generatorOptions:
  labels:
    kustomize.generated.resources: qserv.ingest
  disableNameSuffixHash: true

