commonLabels:
  app: qserv
  org: lsst

resources:
- dev.yaml

configMapGenerator:
- name: config-ingest
  files:
  - ingest.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.generated.resources: qserv.ingest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: INGEST_IMAGE
  newName: qserv/ingest
  newTag: 2021.6.4-rc1-6-g8779a38-dirty
